In [1]:
!pip install sqlalchemy==1.3.9

Collecting sqlalchemy==1.3.9
  Downloading SQLAlchemy-1.3.9.tar.gz (6.0 MB)
     ---------------------------------------- 0.0/6.0 MB ? eta -:--:--
     ---------------------------------------- 0.0/6.0 MB ? eta -:--:--
     ----- ---------------------------------- 0.8/6.0 MB 6.0 MB/s eta 0:00:01
     ------------ --------------------------- 1.8/6.0 MB 5.3 MB/s eta 0:00:01
     ---------------------- ----------------- 3.4/6.0 MB 6.0 MB/s eta 0:00:01
     --------------------------------- ------ 5.0/6.0 MB 6.5 MB/s eta 0:00:01
     ---------------------------------------- 6.0/6.0 MB 6.8 MB/s  0:00:01
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (pyproject.toml): started
  Building wheel for sqlalchemy (pyproject.toml): finished with status 'done'
  Created wheel for sqlalchemy: filename=sqlalchemy-1.3.9-cp313-cp313-win_amd64.whl size=1143040 sha256=d954746a55592d7221d68e634838efc25aad7f02e9e213d04a9771a836faf05c
  Stored in directory: c:\users\cklyf\appdata\local\pip\cache\wheels\7f\0c\92\6ec5ca28eb22ed22341110143de753ec622045fbfc750edb26
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.43
    Uninstalling SQLAlchemy-2.0.43:
      Successfully uninstalled SQLAlchemy-2.0.43
Successfully installed sqlalchemy-1.3.9

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aext-project-filebrowser-server 4.20.0 requires sqlalchemy>=2.0.29, but you have sqlalchemy 1.3.9 which is incompatible.
alembic 1.18.3 requires SQLAlchemy>=1.4.23, but you have sqlalchemy 1.3.9 which is incompatible.

In [2]:
!pip install ipython-sql
!pip install ipython-sql prettytable

Collecting ipython-sql
  Downloading ipython_sql-0.5.0-py3-none-any.whl.metadata (17 kB)
Collecting prettytable (from ipython-sql)
  Downloading prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: ipython in d:\anaconda\lib\site-packages (from ipython-sql) (9.7.0)
Collecting sqlalchemy>=2.0 (from ipython-sql)
  Downloading sqlalchemy-2.0.48-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting sqlparse (from ipython-sql)
  Downloading sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: six in d:\anaconda\lib\site-packages (from ipython-sql) (1.17.0)
Collecting ipython-genutils (from ipython-sql)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl.metadata (755 bytes)
Requirement already satisfied: greenlet>=1 in d:\anaconda\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\anaconda\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: colorama>=0.4.4 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: wcwidth in d:\anaconda\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in d:\anaconda\lib\site-packages (from jedi>=0.18.1->ipython->ipython-sql) (0.8.5)
Requirement already satisfied: executing>=1.2.0 in d:\anaconda\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in d:\anaconda\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure_eval in d:\anaconda\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (0.2.3)
Downloading ipython_sql-0.5.0-py3-none-any.whl (20 kB)
Downloading sqlalchemy-2.0.48-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------  2.1/2.1 MB 14.5 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 12.4 MB/s  0:00:00
Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Downloading prettytable-3.17.0-py3-none-any.whl (34 kB)
Downloading sqlparse-0.5.5-py3-none-any.whl (46 kB)
Installing collected packages: ipython-genutils, sqlparse, sqlalchemy, prettytable, ipython-sql

   ---------------------------------------- 0/5 [ipython-genutils]
   ---------------------------------------- 0/5 [ipython-genutils]
   -------- ------------------------------- 1/5 [sqlparse]
   -------- ------------------------------- 1/5 [sqlparse]
   -------- ------------------------------- 1/5 [sqlparse]
   -------- ------------------------------- 1/5 [sqlparse]
   -------- ------------------------------- 1/5 [sqlparse]
  Attempting uninstall: sqlalchemy
   -------- ------------------------------- 1/5 [sqlparse]
    Found existing installation: SQLAlchemy 1.3.9
   -------- ------------------------------- 1/5 [sqlparse]
   ---------------- ----------------------- 2/5 [sqlalchemy]
    Uninstalling SQLAlchemy-1.3.9:
   ---------------- ----------------------- 2/5 [sqlalchemy]
      Successfully uninstalled SQLAlchemy-1.3.9
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ---------------- ----------------------- 2/5 [sqlalchemy]
   ------------------------ --------------- 3/5 [prettytable]
   ------------------------ --------------- 3/5 [prettytable]
   -------------------------------- ------- 4/5 [ipython-sql]
   -------------------------------- ------- 4/5 [ipython-sql]
   ---------------------------------------- 5/5 [ipython-sql]

Successfully installed ipython-genutils-0.2.0 ipython-sql-0.5.0 prettytable-3.17.0 sqlalchemy-2.0.48 sqlparse-0.5.5
Requirement already satisfied: ipython-sql in d:\anaconda\lib\site-packages (0.5.0)
Requirement already satisfied: prettytable in d:\anaconda\lib\site-packages (3.17.0)
Requirement already satisfied: ipython in d:\anaconda\lib\site-packages (from ipython-sql) (9.7.0)
Requirement already satisfied: sqlalchemy>=2.0 in d:\anaconda\lib\site-packages (from ipython-sql) (2.0.48)
Requirement already satisfied: sqlparse in d:\anaconda\lib\site-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in d:\anaconda\lib\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in d:\anaconda\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in d:\anaconda\lib\site-packages (from prettytable) (0.2.13)
Requirement already satisfied: greenlet>=1 in d:\anaconda\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\anaconda\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: colorama>=0.4.4 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in d:\anaconda\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in d:\anaconda\lib\site-packages (from jedi>=0.18.1->ipython->ipython-sql) (0.8.5)
Requirement already satisfied: executing>=1.2.0 in d:\anaconda\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in d:\anaconda\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure_eval in d:\anaconda\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (0.2.3)

In [3]:
%load_ext sql

In [4]:
import csv, sqlite3
import prettytable
prettytable.DEFAULT = 'DEFAULT'
con = sqlite3.connect("my_data1.db")
cur = con.cursor()

In [5]:
%sql sqlite:///my_data1.db

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

101

In [8]:
query = """
SELECT DISTINCT Launch_Site
FROM SPACEXTBL
"""

In [9]:
pd.read_sql(query, con)

    Launch_Site
0   CCAFS LC-40
1   VAFB SLC-4E
2    KSC LC-39A
3  CCAFS SLC-40

In [10]:
query = """
SELECT *
FROM SPACEXTBL
WHERE Launch_Site LIKE 'CCA%'
LIMIT 5
"""

In [11]:
pd.read_sql(query, con)

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt

In [12]:
query = """
SELECT AVG(Payload_Mass__kg_) AS avg_payload_mass
FROM SPACEXTBL
WHERE Booster_Version = 'F9 v1.1'
"""

In [13]:
pd.read_sql(query, con)

   avg_payload_mass
0            2928.4

In [14]:
query = """
SELECT MIN(Date) AS first_successful_ground_pad
FROM SPACEXTBL
WHERE Landing_Outcome = 'Success (ground pad)'
"""

In [15]:
pd.read_sql(query, con)

  first_successful_ground_pad
0                  2015-12-22

In [16]:
query = """
SELECT DISTINCT Booster_Version
FROM SPACEXTBL
WHERE Landing_Outcome = 'Success (drone ship)'
  AND Payload_Mass__kg_ > 4000
  AND Payload_Mass__kg_ < 6000
"""

In [17]:
pd.read_sql(query, con)

  Booster_Version
0     F9 FT B1022
1     F9 FT B1026
2  F9 FT  B1021.2
3  F9 FT  B1031.2

In [18]:
query = """
SELECT 
    CASE 
        WHEN Mission_Outcome LIKE 'Success%' THEN 'Success'
        ELSE 'Failure'
    END AS outcome_category,
    COUNT(*) AS total_count
FROM SPACEXTBL
GROUP BY outcome_category
"""

In [19]:
pd.read_sql(query, con)

  outcome_category  total_count
0          Failure            1
1          Success          100

In [20]:
query = """
SELECT DISTINCT Booster_Version
FROM SPACEXTBL
WHERE Payload_Mass__kg_ = (
    SELECT MAX(Payload_Mass__kg_)
    FROM SPACEXTBL
)
"""

In [21]:
pd.read_sql(query, con)

   Booster_Version
0    F9 B5 B1048.4
1    F9 B5 B1049.4
2    F9 B5 B1051.3
3    F9 B5 B1056.4
4    F9 B5 B1048.5
5    F9 B5 B1051.4
6    F9 B5 B1049.5
7   F9 B5 B1060.2
8   F9 B5 B1058.3
9    F9 B5 B1051.6
10   F9 B5 B1060.3
11  F9 B5 B1049.7

In [22]:
query = """
SELECT 
    CASE strftime('%m', Date)
        WHEN '01' THEN 'January'
        WHEN '02' THEN 'February'
        WHEN '03' THEN 'March'
        WHEN '04' THEN 'April'
        WHEN '05' THEN 'May'
        WHEN '06' THEN 'June'
        WHEN '07' THEN 'July'
        WHEN '08' THEN 'August'
        WHEN '09' THEN 'September'
        WHEN '10' THEN 'October'
        WHEN '11' THEN 'November'
        WHEN '12' THEN 'December'
    END AS month_name,
    Landing_Outcome,
    Booster_Version,
    Launch_Site
FROM SPACEXTBL
WHERE strftime('%Y', Date) = '2015'
  AND Landing_Outcome LIKE 'Failure%drone ship%'
"""

In [23]:
pd.read_sql(query, con)

  month_name       Landing_Outcome Booster_Version  Launch_Site
0    January  Failure (drone ship)   F9 v1.1 B1012  CCAFS LC-40
1      April  Failure (drone ship)   F9 v1.1 B1015  CCAFS LC-40

In [24]:
query = """
SELECT 
    Landing_Outcome,
    COUNT(*) AS outcome_count,
    RANK() OVER (ORDER BY COUNT(*) DESC) AS rank
FROM SPACEXTBL
WHERE Date BETWEEN '2010-06-04' AND '2017-03-20'
GROUP BY Landing_Outcome
"""

In [25]:
pd.read_sql(query, con)

          Landing_Outcome  outcome_count  rank
0              No attempt             10     1
1    Success (drone ship)              5     2
2    Failure (drone ship)              5     2
3    Success (ground pad)              3     4
4      Controlled (ocean)              3     4
5    Uncontrolled (ocean)              2     6
6     Failure (parachute)              2     6
7  Precluded (drone ship)              1     8